CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(255) NOT NULL,
	`excerpt` text NOT NULL,
	`content` text NOT NULL,
	`authorName` varchar(255) NOT NULL,
	`authorRole` varchar(100),
	`authorAvatar` varchar(500),
	`category` varchar(100) NOT NULL,
	`tags` text,
	`featuredImage` varchar(500),
	`readingTime` int NOT NULL DEFAULT 5,
	`metaTitle` varchar(255),
	`metaDescription` text,
	`isPublished` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `installer_ratings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`installerId` int NOT NULL,
	`leadId` int,
	`reviewerName` varchar(255) NOT NULL,
	`reviewerEmail` varchar(320),
	`reviewerLocation` varchar(100),
	`overallRating` int NOT NULL,
	`communicationRating` int,
	`qualityRating` int,
	`valueRating` int,
	`timelinessRating` int,
	`title` varchar(255),
	`comment` text NOT NULL,
	`systemSize` varchar(50),
	`installationDate` timestamp,
	`isVerified` boolean NOT NULL DEFAULT false,
	`isApproved` boolean NOT NULL DEFAULT false,
	`isPublished` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `installer_ratings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `managed_testimonials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`location` varchar(100) NOT NULL,
	`role` varchar(100),
	`avatar` varchar(500),
	`quote` text NOT NULL,
	`rating` int NOT NULL DEFAULT 5,
	`type` enum('homeowner','installer') NOT NULL DEFAULT 'homeowner',
	`systemSize` varchar(50),
	`savings` varchar(100),
	`isFeatured` boolean NOT NULL DEFAULT false,
	`displayOrder` int NOT NULL DEFAULT 0,
	`isPublished` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `managed_testimonials_id` PRIMARY KEY(`id`)
);
